#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

#Name of the edit tool's item Material. You can find a full list at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
tool: FLINT

#(Optional) data that the plugin looks for to identify the edit tool, such as the damage value of a sword or the pattern of sandstone.
requireToolData: false
toolData: 0

#(Optional) The first "Lore" entry that the plugin looks for to identify the edit tool.
requireToolLore: false
toolLore: Let's get dangerous

#Name of the language file you wish to use
lang: en_US.yml

#If false plugin notifications will be sent to the chat box. If true messages will be sent to the action bar.
sendMessagesToActionBar: true

#Don't set to true unless you want players to see random messages or other undesirable behavior
debug: false