#How many rotations to make a full circle in Coarse adjustment mode
coarse: 12

#How many rotations to make a full circle in Fine adjustment mode
fine: 120

#Name of the edit tool's item Material. You can find a full list at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
tool: FLINT

#Name of the language file you wish to use
lang: en_US.yml